version: '3'
services:
  web:
    build: .
    image: web_server:latest
    container_name: web_server
    command: ["gunicorn", "main:app", "--workers", "4", "--worker-class", "uvicorn.workers.UvicornWorker","--bind", "0.0.0.0:8080"]
    environment:
      - REDIS_URL=redis_server
    networks:
      - network_t
    depends_on:
      - redis

  worker:
    build: .
    image: worker_server:latest
    container_name: worker_server
    command: ["python", "worker.py"]
    environment:
      - REDIS_URL=redis_server
    networks:
      - network_t
    depends_on:
      - redis

  nginx:
    image: nginx:latest
    container_name: nginx_server
    volumes:
      - ./nginx_conf:/etc/nginx/conf.d
    ports:
      - "9999:80"
    networks:
      - network_t
    depends_on:
      - web

  redis:
    image: redis:latest
    container_name: redis_server
    ports:
      - "6379:6379"
    networks:
      - network_t

networks:
  network_t:
    driver: bridge
